#! /bin/bash

# Definición de variables (los directorios terminan SIN /)
version="1.6"
path_jenkins="/var/lib/jenkins"
path_host="/var/www/dwcs"

credencial_id="f3cccce5-d878-4870-a76e-8a4c0812d911"
frecuencia="@hourly"

if test "$#" -ne 4; then
	printf "\nNo hay suficientes parámetros. Usa: \n\t\t$0 [alumnos-CD|alumnos-DWCS] <prefijo-tarea> <id-tarea> <repo-name>\n\n"
	printf "Ejemplo: \t$0 alumnos dwcs t01 edu-php-introphp.git\n\n"

	exit 1
fi

prefijo=$2
tarea=$3
fileAlumnos=$1
path_repo=$4

umask 007
while read username bitbucketAccount
do
echo -e "Configurando proyecto para $username:"
mkdir -p $path_jenkins/jobs/$prefijo-$tarea-$username

fileJobConf=$path_jenkins/jobs/$prefijo-$tarea-$username/config.xml

cat > $fileJobConf <<-EOF
<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job@2.32">
  <actions>
    <org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobAction plugin="pipeline-model-definition@1.3.7"/>
    <org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobPropertyTrackerAction plugin="pipeline-model-definition@1.3.7">
      <jobProperties/>
      <triggers/>
      <parameters/>
      <options/>
    </org.jenkinsci.plugins.pipeline.modeldefinition.actions.DeclarativeJobPropertyTrackerAction>
  </actions>
  <description></description>
  <keepDependencies>false</keepDependencies>
  <properties>
    <org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
      <triggers>
        <hudson.triggers.SCMTrigger>
          <spec>@hourly</spec>
          <ignorePostCommitHooks>false</ignorePostCommitHooks>
        </hudson.triggers.SCMTrigger>
      </triggers>
    </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
  </properties>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@2.65">
    <scm class="hudson.plugins.git.GitSCM" plugin="git@3.9.3">
      <configVersion>2</configVersion>
      <userRemoteConfigs>
        <hudson.plugins.git.UserRemoteConfig>
          <url>git@bitbucket.org:$bitbucketAccount/$path_repo</url>
          <credentialsId>$credencial_id</credentialsId>
        </hudson.plugins.git.UserRemoteConfig>
      </userRemoteConfigs>
      <branches>
        <hudson.plugins.git.BranchSpec>
          <name>*/$username</name>
        </hudson.plugins.git.BranchSpec>
      </branches>
      <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
      <submoduleCfg class="list"/>
      <extensions/>
    </scm>
    <scriptPath>Jenkinsfile</scriptPath>
    <lightweight>true</lightweight>
  </definition>
  <triggers/>
  <disabled>false</disabled>
</flow-definition>
EOF
echo -e "\tCreado fichero $path_jenkins/jobs/$prefijo-$tarea-$username/config.xml"

#cat $fileJobConf
#read -p "Quieres crear un enlace a Apache? (y/n)" -n 1 -r
#if [[ $REPLY =~ ^[Yy]$ ]]
#then
#    mkdir -p $path_host/$prefijo-$username
	# La salida de errores la redirijo a null y no la capturo: https://stackoverflow.com/questions/2292847/how-to-silence-output-in-a-bash-script
#	ln -s $path_jenkins/workspace/$prefijo-$tarea-$username $path_host/$prefijo-$username/$tarea 2> /dev/null
#	exito=$?
#	if [ $exito -eq 0 ];then
#		echo -e "\tCreado enlace de la tarea en virtual host: $path_host/$prefijo-$username/$tarea"
#	else
#		echo -e "\tEnlace ya existente: $path_host/$username/$tarea"
#	fi
#fi

done < "$fileAlumnos"
echo -e "\nTerminado ok"
exit 0


