#! /bin/bash

# Definición de variables (los directorios terminan SIN /)
version="1.6"
path_jenkins="/var/lib/jenkins"

credencial_id="f3cccce5-d878-4870-a76e-8a4c0812d911"
frecuencia="@hourly"

if test "$#" -ne 4; then
	printf "\nNo hay suficientes parámetros. Usa: \n\t\t$0 [alumnos-CD|alumnos-DWCS] <prefijo-tarea> <id-tarea> <repo-name>\n\n"
	printf "Ejemplo: \t$0 alumnos dwcs t01 edu-php-introphp.git\n\n"

	exit 1
fi

prefijo=$2
tarea=$3
fileAlumnos=$1
path_repo=$4

umask 007
while read username bitbucketAccount
do
echo -e "Configurando proyecto para $username:"
mkdir -p $path_jenkins/jobs/$prefijo-$tarea-$username
cat > $path_jenkins/jobs/$prefijo-$tarea-$username/config.xml <<-EOF
<?xml version='1.1' encoding='UTF-8'?>
<maven2-moduleset plugin="maven-plugin@3.2">
  <actions/>
  <description>Tarea generada a partir del script $0 en su versión $version</description>
  <keepDependencies>false</keepDependencies>
  <properties/>
  <scm class="hudson.plugins.git.GitSCM" plugin="git@3.9.3">
    <configVersion>2</configVersion>
    <userRemoteConfigs>
      <hudson.plugins.git.UserRemoteConfig>
        <url>git@bitbucket.org:$bitbucketAccount/$path_repo</url>
        <credentialsId>$credencial_id</credentialsId>
      </hudson.plugins.git.UserRemoteConfig>
    </userRemoteConfigs>
    <branches>
      <hudson.plugins.git.BranchSpec>
        <name>*/$username</name>
      </hudson.plugins.git.BranchSpec>
    </branches>
    <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
    <submoduleCfg class="list"/>
    <extensions/>
  </scm>
  <canRoam>true</canRoam>
  <disabled>false</disabled>
  <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
  <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
  <triggers>
    <hudson.triggers.SCMTrigger>
      <spec>$frecuencia</spec>
      <ignorePostCommitHooks>false</ignorePostCommitHooks>
    </hudson.triggers.SCMTrigger>
  </triggers>
  <concurrentBuild>false</concurrentBuild>
  <rootModule>
    <groupId>edu.xunta.agrasar</groupId>
    <artifactId>POO-Buscaminas</artifactId>
  </rootModule>
  <rootPOM>POO-Buscaminas/pom.xml</rootPOM>
  <goals>clean test jacoco:report</goals>
  <aggregatorStyleBuild>true</aggregatorStyleBuild>
  <incrementalBuild>false</incrementalBuild>
  <ignoreUpstremChanges>false</ignoreUpstremChanges>
  <ignoreUnsuccessfulUpstreams>false</ignoreUnsuccessfulUpstreams>
  <archivingDisabled>false</archivingDisabled>
  <siteArchivingDisabled>false</siteArchivingDisabled>
  <fingerprintingDisabled>false</fingerprintingDisabled>
  <resolveDependencies>false</resolveDependencies>
  <processPlugins>false</processPlugins>
  <mavenValidationLevel>-1</mavenValidationLevel>
  <runHeadless>false</runHeadless>
  <disableTriggerDownstreamProjects>false</disableTriggerDownstreamProjects>
  <blockTriggerWhenBuilding>true</blockTriggerWhenBuilding>
  <settings class="jenkins.mvn.DefaultSettingsProvider"/>
  <globalSettings class="jenkins.mvn.DefaultGlobalSettingsProvider"/>
  <reporters/>
  <publishers>
    <io.jenkins.plugins.coverage.CoveragePublisher plugin="code-coverage-api@1.0.10">
      <adapters>
        <io.jenkins.plugins.coverage.adapter.JacocoReportAdapter>
          <path>POO-Buscaminas/target/site/jacoco/jacoco.xml</path>
          <thresholds class="linked-list"/>
        </io.jenkins.plugins.coverage.adapter.JacocoReportAdapter>
        <hudson.plugins.cobertura.adapter.CoberturaReportAdapter plugin="cobertura@1.13">
          <path>POO-Buscaminas/target/site/cobertura/coverage.xml</path>
          <thresholds class="linked-list"/>
        </hudson.plugins.cobertura.adapter.CoberturaReportAdapter>
        <io.jenkins.plugins.coverage.adapter.IstanbulCoberturaReportAdapter>
          <path>POO-Buscaminas/target/site/cobertura/coverage.xml</path>
          <thresholds class="linked-list"/>
        </io.jenkins.plugins.coverage.adapter.IstanbulCoberturaReportAdapter>
      </adapters>
      <globalThresholds class="linked-list"/>
      <failUnhealthy>false</failUnhealthy>
      <failUnstable>false</failUnstable>
      <failNoReports>false</failNoReports>
      <sourceFileResolver>
        <level>NEVER_STORE</level>
      </sourceFileResolver>
    </io.jenkins.plugins.coverage.CoveragePublisher>
    <xunit plugin="xunit@2.3.3">
      <types>
        <JUnitType>
          <pattern>POO-Buscaminas/target/surefire-reports/TEST-edu.xunta.agrasar.buscaminas.modelo.BuscaminasTest.xml</pattern>
          <skipNoTestFiles>false</skipNoTestFiles>
          <failIfNotNew>true</failIfNotNew>
          <deleteOutputFiles>true</deleteOutputFiles>
          <stopProcessingIfError>true</stopProcessingIfError>
        </JUnitType>
      </types>
      <thresholds/>
      <thresholdMode>1</thresholdMode>
      <extraConfiguration>
        <testTimeMargin>3000</testTimeMargin>
        <reduceLog>true</reduceLog>
      </extraConfiguration>
      <testDataPublishers class="empty-set"/>
    </xunit>
  </publishers>
  <buildWrappers/>
  <prebuilders/>
  <postbuilders/>
  <runPostStepsIfResult>
    <name>FAILURE</name>
    <ordinal>2</ordinal>
    <color>RED</color>
    <completeBuild>true</completeBuild>
  </runPostStepsIfResult>
</maven2-moduleset>
EOF
echo -e "\tCreado fichero $path_jenkins/jobs/$prefijo-$tarea-$username/config.xml"
done < "$fileAlumnos"
echo -e "\nTerminado ok"
exit 0
